<?php

namespace BonnieresInformatique\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findProductByCategory ($category) {

        $query = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.category = :category')
//                ->andWhere('p.available = 1')
                ->orderBy('p.id')
                ->setParameter('category',$category);
        return $query->getQuery()->getResult();
    }

    public function search($product)
    {
        $query = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.name = :product' )
                ->orderBy('p.id')
                ->setParameter('product', $product);
        return $query->getQuery()->getResult();
    }

    public function findArray($array)
    {
        $query = $this->createQueryBuilder('p')
            ->Select('p')
            ->Where('p.id IN (:array)')
            ->setParameter('array', $array);
        return $query->getQuery()->getResult();
    }

}
