<?php

namespace BonnieresInformatique\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAddressRepository extends EntityRepository
{
}
